### PR TITLE
Cleaned up code added test and fixed stuff

### PR DESCRIPTION
**Pull request by magnusvinberg**

### CODE REVIEW

**Review by Gorilliam — APPROVED** [review]
It looks improved upon, so this could work. Although I've yet to actually understand the @Category code.

**Comment by savita2017** [comment]
New test works fine. All changes viewed.

**Review by savita2017 — APPROVED** [review]

**Comment by hallstromsimon** [comment]
Loking  Good

**Review by sophiazhang0111 — APPROVED** [review]
Looks very good. Make some changes and the last is a new test class.

**Pull request merged**
